---
- name: Configure target hosts as LIO gateways for Ceph/Glusterfs
  hosts: ceph_iscsi_gw

  tasks:
    - name: OS Compatibility Check (RHEL 7.3)
      assert:
        that:
          - "ansible_distribution == 'RedHat'"
          - "ansible_distribution_version == '7.3'"

    - name: ensure targetcli (LIO interface) is installed
      yum: name=targetcli state=latest

    - name: ensure package pre-requisites are installed (used by custom modules)
      yum: name={{ item.rpm_name }} state=latest
      with_items:
        - { rpm_name: "python-netifaces" }
        - { rpm_name: "python-netaddr" }

    - name: gateway (tgt) | Configure iSCSI Target (gateway)
      gateway: mode='target' gateway_iqn={{ gateway_iqn }} iscsi_network={{ iscsi_network }}
      register: target

    - name: igw_lun | Configure LUNs (create/map rbds and add to LIO)
      igw_lun: pool={{ item.pool }} image={{item.image}} size={{ item.size }} host={{ item.host }}
      with_items: "{{ rbd_devices }}"
      register: images

    - name: gateway (map) | Map LUNs to the iSCSI target
      gateway: mode='map' gateway_iqn={{ gateway_iqn }} iscsi_network={{ iscsi_network }}
      register: luns

    - name: igw_client | Configure a client connectivity
      igw_client: client_iqn={{ item.client }} image_list={{item.image_list}} auth='chap' credentials={{ item.credentials }} state={{ item.status }}
      with_items: "{{ client_connections }}"
      register: clients

    - name: Save the LIO config if changes are made from prior tasks
      command: /usr/bin/targetcli saveconfig
      when: (target.changed or images.changed or luns.changed or clients.changed)


