---
- name: Configure target hosts as LIO gateways for Ceph/Glusterfs
  hosts: ceph_iscsi_gw

  tasks:
    - name: OS Compatibility Check (RHEL 7.3)
      assert:
        that:
          - "ansible_distribution == 'RedHat'"
          - "ansible_distribution_version == '7.3'"

    # Setup the rbdmap and target services
    - include: svc-enable-el7.yml
      when: ansible_os_family == "RedHat"

    - name: igw_gateway (tgt) | Configure iSCSI Target (gateway)
      igw_gateway: mode='target' gateway_iqn={{ gateway_iqn }} iscsi_network={{ iscsi_network }}
      register: target

    - name: igw_lun | Configure LUNs (create/map rbds and add to LIO)
      igw_lun: pool={{ item.pool }} image={{item.image}} size={{ item.size }} host={{ item.host }}
      with_items: "{{ rbd_devices }}"
      register: images

    - name: igw_gateway (map) | Map LUNs to the iSCSI target
      igw_gateway: mode='map' gateway_iqn={{ gateway_iqn }} iscsi_network={{ iscsi_network }}
      register: luns

    - name: igw_client | Configure a client connectivity
      igw_client: client_iqn={{ item.client }} image_list={{item.image_list}} auth='chap' credentials={{ item.credentials }} state={{ item.status }}
      with_items: "{{ client_connections }}"
      register: clients

    - name: Save the LIO config if changes are made from prior tasks
      command: /usr/bin/targetcli saveconfig
      when: (target.changed or images.changed or luns.changed or clients.changed)


