---
  - name: OS Compatibility Check (RHEL 7.3)
    assert:
      that:
        - "ansible_distribution == 'RedHat'"
        - "ansible_distribution_version == '7.3'"

  - name: ensure targetcli (LIO interface) is installed
    yum: name=targetcli state=latest

  - name: ensure package pre-requisites are installed (used by custom modules)
    yum: name={{ item.rpm_name }} state=latest
    with_items:
      - { rpm_name: "python-netifaces" }
      - { rpm_name: "python-netaddr" }