---
  - name: Check required rpms are installed at latest versions
    yum: name={{ item.rpm }} state=latest
    with_items:
      - rpm: device-mapper-multipath
      - rpm: ceph-iscsi-config

  - name: check multipath.conf file state
    stat: path=/etc/multipath.conf
    register: mpathconf

  - name: configure new multipath.conf
    command: mpathconf  --enable --with_multipathd y --user_friendly_names n --find_multipaths n
    register: conf_created
    when: mpathconf.stat.exists == False

  - name: Read multipath.conf settings
    command: mpathconf
    register: mpathout
    when: mpathconf.stat.exists == True

  - name: ensure user friendly names is disabled
    command: mpathconf  --enable --with_multipathd y --user_friendly_names n --find_multipaths n
    when: conf_created.changed == False and '"find_multipaths is enabled" in mpathout.stdout or "user_friendly_names is enabled" in mpathout.stdout'

  - name: multipathd enabled and started
    service: name=multipathd state=started enabled=yes
